# Generated by Django 3.2.3 on 2023-06-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230610_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
    ]
