# Generated by Django 3.2.3 on 2023-05-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название ингридиента'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientmodel',
            unique_together={('name', 'measurement_unit')},
        ),
    ]
