# Generated by Django 3.2.3 on 2023-05-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20230530_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipemodel',
            name='ingredient',
            field=models.ForeignKey(default='Какой то ингредиент', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ingredient_recipe', to='recipe.ingredientmodel', verbose_name='Ингредиент (id)'),
        ),
    ]
