# Generated by Django 3.2.3 on 2023-05-31 09:34

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_ingredientrecipemodel_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipemodel',
            name='amount',
            field=models.FloatField(validators=[core.validators.validate_amount_more_zero], verbose_name='Кол-во ингредиента'),
        ),
    ]
