# Generated by Django 3.2.3 on 2023-06-22 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_tagrecipemodel_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Время приготовления не может быть меньше 1.')], verbose_name='Время (мин.)'),
        ),
    ]
